services:
  mysql:
    image: mysql:8.0
    container_name: mafia-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mafiadb
      MYSQL_USER: mafiauser
      MYSQL_PASSWORD: mafiapass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: mafia-phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: mafiauser
      PMA_PASSWORD: mafiapass
    ports:
      - "8081:80"
    depends_on:
      - mysql
    restart: unless-stopped

volumes:
  mysql_data: 